/// Flutter icons Customicons
/// Copyright (C) 2022 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  Customicons
///      fonts:
///       - asset: fonts/Customicons.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class Customicons {
  Customicons._();

  static const _kFontFam = 'Customicons';
  static const String? _kFontPkg = null;

  static const IconData close = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData group = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData filter = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData search = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData notification = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData setting = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData document = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData home = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData chat = IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData call = IconData(0xe809, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData location = IconData(0xe80a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData message = IconData(0xe80b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData profile = IconData(0xe80c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData password = IconData(0xe80d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData arrow = IconData(0xe80e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
